- hosts: 54.64.193.21
  remote_user: ec2-user
  sudo: yes
  tasks:
  - name: python mysql install
    command: yum install -y MySQL-python

  - name: create database
    mysql_db: name=zabbix state=present encoding=utf8

  - name: create database user
    mysql_user: name=zabbix password=8apDev68 priv=zabbix.*:ALL state=present

  - name: schema_import
    shell: mysql -uroot zabbix < /usr/share/doc/zabbix-server-mysql-2.2.6/create/schema.sql
    ignore_errors: True

  - name: image_import
    shell: mysql -uroot zabbix < /usr/share/doc/zabbix-server-mysql-2.2.6/create/images.sql
    ignore_errors: True

  - name: data_import
    shell: mysql -uroot zabbix < /usr/share/doc/zabbix-server-mysql-2.2.6/create/data.sql
    ignore_errors: True
  - name: "conf"
    lineinfile: dest=/etc/zabbix/zabbix_server.conf regexp='^# DBPassword='  line=DBPassword=8apDev68
