- hosts: 54.64.133.2
  remote_user: ec2-user
  sudo: yes
  tasks:
  - name: ensure apache is at the latest version
    yum: pkg={{item}} state=installed
    with_items:
      - httpd
      - php
      - php-pear
      - php-mysql
      - php-mbstring
      - php-gd
      - php-mcrypt
      - php-pecl-apc
      - mysql-server

  - name: ensure apache is running and enabled
    service: name=httpd state=started enabled=yes

  - name: repo_regist
    command: rpm -ivh http://repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-release-2.2-1.el6.noarch.rpm
    ignore_errors: True

  - name: ensure zabbix is at the latest version
    yum: pkg={{item}} state=installed
    with_items:
      - zabbix-server-mysql
      - zabbix-web-mysql
      - zabbix-web-japanese
      - zabbix-agent
      - zabbix-get

  - name: repo_disable
    lineinfile: dest=/etc/yum.repos.d/zabbix.repo regexp=^enable line=enable=1

  - name: "rename my.cnf"
    command: mv /etc/my.cnf /etc/my.cnf.org

  - name: "conf_cp"
    template: src=/tmp/my.txt dest=/etc/my.cnf owner=root group=root mode=644

  - name: ensure mysqld is running and enabled
    service: name=mysqld state=started enabled=yes
